version: "3"
services:
  meta-tx-gateway:
    build:
      context: ../.
      dockerfile: ./examples/meta-tx-gateway/Dockerfile
    image: meta-tx-gateway:20220912142900
    ports:
      - "8888:8888"
    environment:
      - CHAIN_ID=31337
      - PRIVATE_KEY=0x316b234f5fea007dcc40404188b588fb90cb9bb1e33fc163e212eab2f8565293 # ACCOUNT_9 from ./contracts/accounts.js
      - RPC_NODE=http://host.docker.internal:8545
    depends_on:
      - hardhat-node
    command: ["sh", "-c", "sleep 3 && npm run start"]

  hardhat-node:
    build: ../contracts
    image: hardhat-node:a24305388c8a2b86cb59667e184677ab8862ebf2
    ports:
      - "8545:8545"

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres
      - hardhat-node
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "localhost:http://host.docker.internal:8545"
      GRAPH_LOG: info
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: "true"

  ipfs:
    image: ipfs/go-ipfs:master-2022-05-25-e8f1ce0
    ports:
      - "5001:5001"
    volumes:
      - ./ipfs-config.sh:/container-init.d/ipfs-config.sh

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
