// TODO: add test for handleDisputeRaisedEvent
// TODO: add test for handleDisputeRetractedEvent
// TODO: add test for handleDisputeTimeoutExtendedEvent
// TODO: add test for handleDisputeExpiredEvent
// TODO: add test for handleDisputeResolvedEvent
// TODO: add test for handleDisputeEscalatedEvent
// TODO: add test for handleDisputeDecidedEvent
// TODO: add test for handleEscalatedDisputeRefusedEvent
// TODO: add test for handleEscalatedDisputeExpiredEvent
