/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace BosonTypes {
  export type OfferStruct = {
    id: BigNumberish;
    price: BigNumberish;
    deposit: BigNumberish;
    penalty: BigNumberish;
    quantity: BigNumberish;
    validFromDate: BigNumberish;
    validUntilDate: BigNumberish;
    redeemableDate: BigNumberish;
    fulfillmentPeriodDuration: BigNumberish;
    voucherValidDuration: BigNumberish;
    seller: string;
    exchangeToken: string;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
  };

  export type OfferStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    boolean
  ] & {
    id: BigNumber;
    price: BigNumber;
    deposit: BigNumber;
    penalty: BigNumber;
    quantity: BigNumber;
    validFromDate: BigNumber;
    validUntilDate: BigNumber;
    redeemableDate: BigNumber;
    fulfillmentPeriodDuration: BigNumber;
    voucherValidDuration: BigNumber;
    seller: string;
    exchangeToken: string;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
  };
}

export interface IBosonOfferHandlerInterface extends utils.Interface {
  contractName: "IBosonOfferHandler";
  functions: {
    "createOffer((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,address,string,string,bool))": FunctionFragment;
    "getNextOfferId()": FunctionFragment;
    "getOffer(uint256)": FunctionFragment;
    "voidOffer(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createOffer",
    values: [BosonTypes.OfferStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextOfferId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voidOffer",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextOfferId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voidOffer", data: BytesLike): Result;

  events: {
    "OfferCreated(uint256,address,tuple)": EventFragment;
    "OfferVoided(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OfferCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferVoided"): EventFragment;
}

export type OfferCreatedEvent = TypedEvent<
  [BigNumber, string, BosonTypes.OfferStructOutput],
  { offerId: BigNumber; seller: string; offer: BosonTypes.OfferStructOutput }
>;

export type OfferCreatedEventFilter = TypedEventFilter<OfferCreatedEvent>;

export type OfferVoidedEvent = TypedEvent<
  [BigNumber, string],
  { offerId: BigNumber; seller: string }
>;

export type OfferVoidedEventFilter = TypedEventFilter<OfferVoidedEvent>;

export interface IBosonOfferHandler extends BaseContract {
  contractName: "IBosonOfferHandler";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBosonOfferHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getNextOfferId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nextOfferId: BigNumber }>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BosonTypes.OfferStructOutput] & {
        success: boolean;
        offer: BosonTypes.OfferStructOutput;
      }
    >;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createOffer(
    _offer: BosonTypes.OfferStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

  getOffer(
    _offerId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BosonTypes.OfferStructOutput] & {
      success: boolean;
      offer: BosonTypes.OfferStructOutput;
    }
  >;

  voidOffer(
    _offerId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BosonTypes.OfferStructOutput] & {
        success: boolean;
        offer: BosonTypes.OfferStructOutput;
      }
    >;

    voidOffer(_offerId: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OfferCreated(uint256,address,tuple)"(
      offerId?: BigNumberish | null,
      seller?: string | null,
      offer?: null
    ): OfferCreatedEventFilter;
    OfferCreated(
      offerId?: BigNumberish | null,
      seller?: string | null,
      offer?: null
    ): OfferCreatedEventFilter;

    "OfferVoided(uint256,address)"(
      offerId?: BigNumberish | null,
      seller?: string | null
    ): OfferVoidedEventFilter;
    OfferVoided(
      offerId?: BigNumberish | null,
      seller?: string | null
    ): OfferVoidedEventFilter;
  };

  estimateGas: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getNextOfferId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
