/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace BosonTypes {
  export type BundleStruct = {
    id: BigNumberish;
    sellerId: BigNumberish;
    offerIds: BigNumberish[];
    twinIds: BigNumberish[];
  };

  export type BundleStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber[]
  ] & {
    id: BigNumber;
    sellerId: BigNumber;
    offerIds: BigNumber[];
    twinIds: BigNumber[];
  };

  export type BuyerStruct = {
    id: BigNumberish;
    wallet: string;
    active: boolean;
  };

  export type BuyerStructOutput = [BigNumber, string, boolean] & {
    id: BigNumber;
    wallet: string;
    active: boolean;
  };

  export type DisputeResolverStruct = {
    id: BigNumberish;
    wallet: string;
    active: boolean;
  };

  export type DisputeResolverStructOutput = [BigNumber, string, boolean] & {
    id: BigNumber;
    wallet: string;
    active: boolean;
  };

  export type ConditionStruct = {
    method: BigNumberish;
    tokenAddress: string;
    tokenId: BigNumberish;
    threshold: BigNumberish;
  };

  export type ConditionStructOutput = [number, string, BigNumber, BigNumber] & {
    method: number;
    tokenAddress: string;
    tokenId: BigNumber;
    threshold: BigNumber;
  };

  export type GroupStruct = {
    id: BigNumberish;
    sellerId: BigNumberish;
    offerIds: BigNumberish[];
    condition: BosonTypes.ConditionStruct;
  };

  export type GroupStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber[],
    BosonTypes.ConditionStructOutput
  ] & {
    id: BigNumber;
    sellerId: BigNumber;
    offerIds: BigNumber[];
    condition: BosonTypes.ConditionStructOutput;
  };

  export type OfferStruct = {
    id: BigNumberish;
    sellerId: BigNumberish;
    price: BigNumberish;
    sellerDeposit: BigNumberish;
    protocolFee: BigNumberish;
    buyerCancelPenalty: BigNumberish;
    quantityAvailable: BigNumberish;
    exchangeToken: string;
    disputeResolverId: BigNumberish;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
  };

  export type OfferStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    boolean
  ] & {
    id: BigNumber;
    sellerId: BigNumber;
    price: BigNumber;
    sellerDeposit: BigNumber;
    protocolFee: BigNumber;
    buyerCancelPenalty: BigNumber;
    quantityAvailable: BigNumber;
    exchangeToken: string;
    disputeResolverId: BigNumber;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
  };

  export type OfferDatesStruct = {
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    voucherRedeemableFrom: BigNumberish;
    voucherRedeemableUntil: BigNumberish;
  };

  export type OfferDatesStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    validFrom: BigNumber;
    validUntil: BigNumber;
    voucherRedeemableFrom: BigNumber;
    voucherRedeemableUntil: BigNumber;
  };

  export type OfferDurationsStruct = {
    fulfillmentPeriod: BigNumberish;
    voucherValid: BigNumberish;
    resolutionPeriod: BigNumberish;
  };

  export type OfferDurationsStructOutput = [BigNumber, BigNumber, BigNumber] & {
    fulfillmentPeriod: BigNumber;
    voucherValid: BigNumber;
    resolutionPeriod: BigNumber;
  };

  export type SellerStruct = {
    id: BigNumberish;
    operator: string;
    admin: string;
    clerk: string;
    treasury: string;
    active: boolean;
  };

  export type SellerStructOutput = [
    BigNumber,
    string,
    string,
    string,
    string,
    boolean
  ] & {
    id: BigNumber;
    operator: string;
    admin: string;
    clerk: string;
    treasury: string;
    active: boolean;
  };

  export type TwinStruct = {
    id: BigNumberish;
    sellerId: BigNumberish;
    supplyAvailable: BigNumberish;
    supplyIds: BigNumberish[];
    tokenId: BigNumberish;
    tokenAddress: string;
    tokenType: BigNumberish;
  };

  export type TwinStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber,
    string,
    number
  ] & {
    id: BigNumber;
    sellerId: BigNumber;
    supplyAvailable: BigNumber;
    supplyIds: BigNumber[];
    tokenId: BigNumber;
    tokenAddress: string;
    tokenType: number;
  };
}

export interface IBosonOrchestrationHandlerInterface extends utils.Interface {
  contractName: "IBosonOrchestrationHandler";
  functions: {
    "createOfferAddToGroup((uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),uint256)": FunctionFragment;
    "createOfferAndTwinWithBundle((uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,uint256,uint256,uint256[],uint256,address,uint8))": FunctionFragment;
    "createOfferWithCondition((uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint8,address,uint256,uint256))": FunctionFragment;
    "createOfferWithConditionAndTwinAndBundle((uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint8,address,uint256,uint256),(uint256,uint256,uint256,uint256[],uint256,address,uint8))": FunctionFragment;
    "createSellerAndOffer((uint256,address,address,address,address,bool),(uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256))": FunctionFragment;
    "createSellerAndOfferAndTwinWithBundle((uint256,address,address,address,address,bool),(uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,uint256,uint256,uint256[],uint256,address,uint8))": FunctionFragment;
    "createSellerAndOfferWithCondition((uint256,address,address,address,address,bool),(uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint8,address,uint256,uint256))": FunctionFragment;
    "createSellerAndOfferWithConditionAndTwinAndBundle((uint256,address,address,address,address,bool),(uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,uint256,string,string,bool),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint8,address,uint256,uint256),(uint256,uint256,uint256,uint256[],uint256,address,uint8))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createOfferAddToGroup",
    values: [
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createOfferAndTwinWithBundle",
    values: [
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.TwinStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createOfferWithCondition",
    values: [
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.ConditionStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createOfferWithConditionAndTwinAndBundle",
    values: [
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.ConditionStruct,
      BosonTypes.TwinStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellerAndOffer",
    values: [
      BosonTypes.SellerStruct,
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellerAndOfferAndTwinWithBundle",
    values: [
      BosonTypes.SellerStruct,
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.TwinStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellerAndOfferWithCondition",
    values: [
      BosonTypes.SellerStruct,
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.ConditionStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellerAndOfferWithConditionAndTwinAndBundle",
    values: [
      BosonTypes.SellerStruct,
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.ConditionStruct,
      BosonTypes.TwinStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createOfferAddToGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOfferAndTwinWithBundle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOfferWithCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOfferWithConditionAndTwinAndBundle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellerAndOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellerAndOfferAndTwinWithBundle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellerAndOfferWithCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellerAndOfferWithConditionAndTwinAndBundle",
    data: BytesLike
  ): Result;

  events: {
    "BundleCreated(uint256,uint256,tuple,address)": EventFragment;
    "BundleDeleted(uint256,uint256,address)": EventFragment;
    "BundleUpdated(uint256,uint256,tuple,address)": EventFragment;
    "BuyerCreated(uint256,tuple,address)": EventFragment;
    "BuyerUpdated(uint256,tuple,address)": EventFragment;
    "DisputeResolverCreated(uint256,tuple,address)": EventFragment;
    "DisputeResolverUpdated(uint256,tuple,address)": EventFragment;
    "GroupCreated(uint256,uint256,tuple,address)": EventFragment;
    "GroupUpdated(uint256,uint256,tuple,address)": EventFragment;
    "OfferCreated(uint256,uint256,tuple,tuple,tuple,address)": EventFragment;
    "OfferExtended(uint256,uint256,uint256,address)": EventFragment;
    "OfferVoided(uint256,uint256,address)": EventFragment;
    "SellerCreated(uint256,tuple,address)": EventFragment;
    "SellerUpdated(uint256,tuple,address)": EventFragment;
    "TwinCreated(uint256,uint256,tuple,address)": EventFragment;
    "TwinDeleted(uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BundleCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BundleDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BundleUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyerCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisputeResolverCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisputeResolverUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GroupCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GroupUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferExtended"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferVoided"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellerCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwinCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwinDeleted"): EventFragment;
}

export type BundleCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.BundleStructOutput, string],
  {
    bundleId: BigNumber;
    sellerId: BigNumber;
    bundle: BosonTypes.BundleStructOutput;
    executedBy: string;
  }
>;

export type BundleCreatedEventFilter = TypedEventFilter<BundleCreatedEvent>;

export type BundleDeletedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { bundleId: BigNumber; sellerId: BigNumber; executedBy: string }
>;

export type BundleDeletedEventFilter = TypedEventFilter<BundleDeletedEvent>;

export type BundleUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.BundleStructOutput, string],
  {
    bundleId: BigNumber;
    sellerId: BigNumber;
    bundle: BosonTypes.BundleStructOutput;
    executedBy: string;
  }
>;

export type BundleUpdatedEventFilter = TypedEventFilter<BundleUpdatedEvent>;

export type BuyerCreatedEvent = TypedEvent<
  [BigNumber, BosonTypes.BuyerStructOutput, string],
  {
    buyerId: BigNumber;
    buyer: BosonTypes.BuyerStructOutput;
    executedBy: string;
  }
>;

export type BuyerCreatedEventFilter = TypedEventFilter<BuyerCreatedEvent>;

export type BuyerUpdatedEvent = TypedEvent<
  [BigNumber, BosonTypes.BuyerStructOutput, string],
  {
    buyerId: BigNumber;
    buyer: BosonTypes.BuyerStructOutput;
    executedBy: string;
  }
>;

export type BuyerUpdatedEventFilter = TypedEventFilter<BuyerUpdatedEvent>;

export type DisputeResolverCreatedEvent = TypedEvent<
  [BigNumber, BosonTypes.DisputeResolverStructOutput, string],
  {
    disputeResolverId: BigNumber;
    disputeResolver: BosonTypes.DisputeResolverStructOutput;
    executedBy: string;
  }
>;

export type DisputeResolverCreatedEventFilter =
  TypedEventFilter<DisputeResolverCreatedEvent>;

export type DisputeResolverUpdatedEvent = TypedEvent<
  [BigNumber, BosonTypes.DisputeResolverStructOutput, string],
  {
    disputeResolverId: BigNumber;
    disputeResolver: BosonTypes.DisputeResolverStructOutput;
    executedBy: string;
  }
>;

export type DisputeResolverUpdatedEventFilter =
  TypedEventFilter<DisputeResolverUpdatedEvent>;

export type GroupCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.GroupStructOutput, string],
  {
    groupId: BigNumber;
    sellerId: BigNumber;
    group: BosonTypes.GroupStructOutput;
    executedBy: string;
  }
>;

export type GroupCreatedEventFilter = TypedEventFilter<GroupCreatedEvent>;

export type GroupUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.GroupStructOutput, string],
  {
    groupId: BigNumber;
    sellerId: BigNumber;
    group: BosonTypes.GroupStructOutput;
    executedBy: string;
  }
>;

export type GroupUpdatedEventFilter = TypedEventFilter<GroupUpdatedEvent>;

export type OfferCreatedEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    BosonTypes.OfferStructOutput,
    BosonTypes.OfferDatesStructOutput,
    BosonTypes.OfferDurationsStructOutput,
    string
  ],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    offer: BosonTypes.OfferStructOutput;
    offerDates: BosonTypes.OfferDatesStructOutput;
    offerDurations: BosonTypes.OfferDurationsStructOutput;
    executedBy: string;
  }
>;

export type OfferCreatedEventFilter = TypedEventFilter<OfferCreatedEvent>;

export type OfferExtendedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    validUntilDate: BigNumber;
    executedBy: string;
  }
>;

export type OfferExtendedEventFilter = TypedEventFilter<OfferExtendedEvent>;

export type OfferVoidedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { offerId: BigNumber; sellerId: BigNumber; executedBy: string }
>;

export type OfferVoidedEventFilter = TypedEventFilter<OfferVoidedEvent>;

export type SellerCreatedEvent = TypedEvent<
  [BigNumber, BosonTypes.SellerStructOutput, string],
  {
    sellerId: BigNumber;
    seller: BosonTypes.SellerStructOutput;
    executedBy: string;
  }
>;

export type SellerCreatedEventFilter = TypedEventFilter<SellerCreatedEvent>;

export type SellerUpdatedEvent = TypedEvent<
  [BigNumber, BosonTypes.SellerStructOutput, string],
  {
    sellerId: BigNumber;
    seller: BosonTypes.SellerStructOutput;
    executedBy: string;
  }
>;

export type SellerUpdatedEventFilter = TypedEventFilter<SellerUpdatedEvent>;

export type TwinCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.TwinStructOutput, string],
  {
    twinId: BigNumber;
    sellerId: BigNumber;
    twin: BosonTypes.TwinStructOutput;
    executedBy: string;
  }
>;

export type TwinCreatedEventFilter = TypedEventFilter<TwinCreatedEvent>;

export type TwinDeletedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { twinId: BigNumber; sellerId: BigNumber; executedBy: string }
>;

export type TwinDeletedEventFilter = TypedEventFilter<TwinDeletedEvent>;

export interface IBosonOrchestrationHandler extends BaseContract {
  contractName: "IBosonOrchestrationHandler";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBosonOrchestrationHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createOfferAddToGroup(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createOfferAndTwinWithBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createOfferWithCondition(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createOfferWithConditionAndTwinAndBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSellerAndOffer(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSellerAndOfferAndTwinWithBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSellerAndOfferWithCondition(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSellerAndOfferWithConditionAndTwinAndBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createOfferAddToGroup(
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _groupId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createOfferAndTwinWithBundle(
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _twin: BosonTypes.TwinStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createOfferWithCondition(
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _condition: BosonTypes.ConditionStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createOfferWithConditionAndTwinAndBundle(
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _condition: BosonTypes.ConditionStruct,
    _twin: BosonTypes.TwinStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSellerAndOffer(
    _seller: BosonTypes.SellerStruct,
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSellerAndOfferAndTwinWithBundle(
    _seller: BosonTypes.SellerStruct,
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _twin: BosonTypes.TwinStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSellerAndOfferWithCondition(
    _seller: BosonTypes.SellerStruct,
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _condition: BosonTypes.ConditionStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSellerAndOfferWithConditionAndTwinAndBundle(
    _seller: BosonTypes.SellerStruct,
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _condition: BosonTypes.ConditionStruct,
    _twin: BosonTypes.TwinStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createOfferAddToGroup(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _groupId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createOfferAndTwinWithBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createOfferWithCondition(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createOfferWithConditionAndTwinAndBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createSellerAndOffer(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createSellerAndOfferAndTwinWithBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createSellerAndOfferWithCondition(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createSellerAndOfferWithConditionAndTwinAndBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BundleCreated(uint256,uint256,tuple,address)"(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      bundle?: null,
      executedBy?: string | null
    ): BundleCreatedEventFilter;
    BundleCreated(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      bundle?: null,
      executedBy?: string | null
    ): BundleCreatedEventFilter;

    "BundleDeleted(uint256,uint256,address)"(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): BundleDeletedEventFilter;
    BundleDeleted(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): BundleDeletedEventFilter;

    "BundleUpdated(uint256,uint256,tuple,address)"(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      bundle?: null,
      executedBy?: string | null
    ): BundleUpdatedEventFilter;
    BundleUpdated(
      bundleId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      bundle?: null,
      executedBy?: string | null
    ): BundleUpdatedEventFilter;

    "BuyerCreated(uint256,tuple,address)"(
      buyerId?: BigNumberish | null,
      buyer?: null,
      executedBy?: string | null
    ): BuyerCreatedEventFilter;
    BuyerCreated(
      buyerId?: BigNumberish | null,
      buyer?: null,
      executedBy?: string | null
    ): BuyerCreatedEventFilter;

    "BuyerUpdated(uint256,tuple,address)"(
      buyerId?: BigNumberish | null,
      buyer?: null,
      executedBy?: string | null
    ): BuyerUpdatedEventFilter;
    BuyerUpdated(
      buyerId?: BigNumberish | null,
      buyer?: null,
      executedBy?: string | null
    ): BuyerUpdatedEventFilter;

    "DisputeResolverCreated(uint256,tuple,address)"(
      disputeResolverId?: BigNumberish | null,
      disputeResolver?: null,
      executedBy?: string | null
    ): DisputeResolverCreatedEventFilter;
    DisputeResolverCreated(
      disputeResolverId?: BigNumberish | null,
      disputeResolver?: null,
      executedBy?: string | null
    ): DisputeResolverCreatedEventFilter;

    "DisputeResolverUpdated(uint256,tuple,address)"(
      disputeResolverId?: BigNumberish | null,
      disputeResolver?: null,
      executedBy?: string | null
    ): DisputeResolverUpdatedEventFilter;
    DisputeResolverUpdated(
      disputeResolverId?: BigNumberish | null,
      disputeResolver?: null,
      executedBy?: string | null
    ): DisputeResolverUpdatedEventFilter;

    "GroupCreated(uint256,uint256,tuple,address)"(
      groupId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      group?: null,
      executedBy?: string | null
    ): GroupCreatedEventFilter;
    GroupCreated(
      groupId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      group?: null,
      executedBy?: string | null
    ): GroupCreatedEventFilter;

    "GroupUpdated(uint256,uint256,tuple,address)"(
      groupId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      group?: null,
      executedBy?: string | null
    ): GroupUpdatedEventFilter;
    GroupUpdated(
      groupId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      group?: null,
      executedBy?: string | null
    ): GroupUpdatedEventFilter;

    "OfferCreated(uint256,uint256,tuple,tuple,tuple,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      offer?: null,
      offerDates?: null,
      offerDurations?: null,
      executedBy?: string | null
    ): OfferCreatedEventFilter;
    OfferCreated(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      offer?: null,
      offerDates?: null,
      offerDurations?: null,
      executedBy?: string | null
    ): OfferCreatedEventFilter;

    "OfferExtended(uint256,uint256,uint256,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      validUntilDate?: null,
      executedBy?: string | null
    ): OfferExtendedEventFilter;
    OfferExtended(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      validUntilDate?: null,
      executedBy?: string | null
    ): OfferExtendedEventFilter;

    "OfferVoided(uint256,uint256,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): OfferVoidedEventFilter;
    OfferVoided(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): OfferVoidedEventFilter;

    "SellerCreated(uint256,tuple,address)"(
      sellerId?: BigNumberish | null,
      seller?: null,
      executedBy?: string | null
    ): SellerCreatedEventFilter;
    SellerCreated(
      sellerId?: BigNumberish | null,
      seller?: null,
      executedBy?: string | null
    ): SellerCreatedEventFilter;

    "SellerUpdated(uint256,tuple,address)"(
      sellerId?: BigNumberish | null,
      seller?: null,
      executedBy?: string | null
    ): SellerUpdatedEventFilter;
    SellerUpdated(
      sellerId?: BigNumberish | null,
      seller?: null,
      executedBy?: string | null
    ): SellerUpdatedEventFilter;

    "TwinCreated(uint256,uint256,tuple,address)"(
      twinId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      twin?: null,
      executedBy?: string | null
    ): TwinCreatedEventFilter;
    TwinCreated(
      twinId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      twin?: null,
      executedBy?: string | null
    ): TwinCreatedEventFilter;

    "TwinDeleted(uint256,uint256,address)"(
      twinId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): TwinDeletedEventFilter;
    TwinDeleted(
      twinId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      executedBy?: string | null
    ): TwinDeletedEventFilter;
  };

  estimateGas: {
    createOfferAddToGroup(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createOfferAndTwinWithBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createOfferWithCondition(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createOfferWithConditionAndTwinAndBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSellerAndOffer(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSellerAndOfferAndTwinWithBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSellerAndOfferWithCondition(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSellerAndOfferWithConditionAndTwinAndBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createOfferAddToGroup(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _groupId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createOfferAndTwinWithBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createOfferWithCondition(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createOfferWithConditionAndTwinAndBundle(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSellerAndOffer(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSellerAndOfferAndTwinWithBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSellerAndOfferWithCondition(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSellerAndOfferWithConditionAndTwinAndBundle(
      _seller: BosonTypes.SellerStruct,
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _condition: BosonTypes.ConditionStruct,
      _twin: BosonTypes.TwinStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
