/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace BosonTypes {
  export type RoyaltyInfoStruct = { recipients: string[]; bps: BigNumberish[] };

  export type RoyaltyInfoStructOutput = [string[], BigNumber[]] & {
    recipients: string[];
    bps: BigNumber[];
  };

  export type OfferStruct = {
    id: BigNumberish;
    sellerId: BigNumberish;
    price: BigNumberish;
    sellerDeposit: BigNumberish;
    buyerCancelPenalty: BigNumberish;
    quantityAvailable: BigNumberish;
    exchangeToken: string;
    priceType: BigNumberish;
    creator: BigNumberish;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
    collectionIndex: BigNumberish;
    royaltyInfo: BosonTypes.RoyaltyInfoStruct[];
    buyerId: BigNumberish;
  };

  export type OfferStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    number,
    number,
    string,
    string,
    boolean,
    BigNumber,
    BosonTypes.RoyaltyInfoStructOutput[],
    BigNumber
  ] & {
    id: BigNumber;
    sellerId: BigNumber;
    price: BigNumber;
    sellerDeposit: BigNumber;
    buyerCancelPenalty: BigNumber;
    quantityAvailable: BigNumber;
    exchangeToken: string;
    priceType: number;
    creator: number;
    metadataUri: string;
    metadataHash: string;
    voided: boolean;
    collectionIndex: BigNumber;
    royaltyInfo: BosonTypes.RoyaltyInfoStructOutput[];
    buyerId: BigNumber;
  };

  export type OfferDatesStruct = {
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    voucherRedeemableFrom: BigNumberish;
    voucherRedeemableUntil: BigNumberish;
  };

  export type OfferDatesStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    validFrom: BigNumber;
    validUntil: BigNumber;
    voucherRedeemableFrom: BigNumber;
    voucherRedeemableUntil: BigNumber;
  };

  export type OfferDurationsStruct = {
    disputePeriod: BigNumberish;
    voucherValid: BigNumberish;
    resolutionPeriod: BigNumberish;
  };

  export type OfferDurationsStructOutput = [BigNumber, BigNumber, BigNumber] & {
    disputePeriod: BigNumber;
    voucherValid: BigNumber;
    resolutionPeriod: BigNumber;
  };

  export type DisputeResolutionTermsStruct = {
    disputeResolverId: BigNumberish;
    escalationResponsePeriod: BigNumberish;
    feeAmount: BigNumberish;
    buyerEscalationDeposit: BigNumberish;
    mutualizerAddress: string;
  };

  export type DisputeResolutionTermsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    disputeResolverId: BigNumber;
    escalationResponsePeriod: BigNumber;
    feeAmount: BigNumber;
    buyerEscalationDeposit: BigNumber;
    mutualizerAddress: string;
  };

  export type OfferFeesStruct = {
    protocolFee: BigNumberish;
    agentFee: BigNumberish;
  };

  export type OfferFeesStructOutput = [BigNumber, BigNumber] & {
    protocolFee: BigNumber;
    agentFee: BigNumber;
  };

  export type DRParametersStruct = {
    disputeResolverId: BigNumberish;
    mutualizerAddress: string;
  };

  export type DRParametersStructOutput = [BigNumber, string] & {
    disputeResolverId: BigNumber;
    mutualizerAddress: string;
  };

  export type ConditionStruct = {
    method: BigNumberish;
    tokenType: BigNumberish;
    tokenAddress: string;
    gating: BigNumberish;
    minTokenId: BigNumberish;
    threshold: BigNumberish;
    maxCommits: BigNumberish;
    maxTokenId: BigNumberish;
  };

  export type ConditionStructOutput = [
    number,
    number,
    string,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    method: number;
    tokenType: number;
    tokenAddress: string;
    gating: number;
    minTokenId: BigNumber;
    threshold: BigNumber;
    maxCommits: BigNumber;
    maxTokenId: BigNumber;
  };

  export type FullOfferStruct = {
    offer: BosonTypes.OfferStruct;
    offerDates: BosonTypes.OfferDatesStruct;
    offerDurations: BosonTypes.OfferDurationsStruct;
    drParameters: BosonTypes.DRParametersStruct;
    condition: BosonTypes.ConditionStruct;
    agentId: BigNumberish;
    feeLimit: BigNumberish;
    useDepositedFunds: boolean;
  };

  export type FullOfferStructOutput = [
    BosonTypes.OfferStructOutput,
    BosonTypes.OfferDatesStructOutput,
    BosonTypes.OfferDurationsStructOutput,
    BosonTypes.DRParametersStructOutput,
    BosonTypes.ConditionStructOutput,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    offer: BosonTypes.OfferStructOutput;
    offerDates: BosonTypes.OfferDatesStructOutput;
    offerDurations: BosonTypes.OfferDurationsStructOutput;
    drParameters: BosonTypes.DRParametersStructOutput;
    condition: BosonTypes.ConditionStructOutput;
    agentId: BigNumber;
    feeLimit: BigNumber;
    useDepositedFunds: boolean;
  };
}

export interface IBosonOfferHandlerInterface extends utils.Interface {
  contractName: "IBosonOfferHandler";
  functions: {
    "createOffer((uint256,uint256,uint256,uint256,uint256,uint256,address,uint8,uint8,string,string,bool,uint256,(address[],uint256[])[],uint256),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,address),uint256,uint256)": FunctionFragment;
    "createOfferBatch((uint256,uint256,uint256,uint256,uint256,uint256,address,uint8,uint8,string,string,bool,uint256,(address[],uint256[])[],uint256)[],(uint256,uint256,uint256,uint256)[],(uint256,uint256,uint256)[],(uint256,address)[],uint256[],uint256[])": FunctionFragment;
    "extendOffer(uint256,uint256)": FunctionFragment;
    "extendOfferBatch(uint256[],uint256)": FunctionFragment;
    "getAgentIdByOffer(uint256)": FunctionFragment;
    "getNextOfferId()": FunctionFragment;
    "getOffer(uint256)": FunctionFragment;
    "getOfferHash(((uint256,uint256,uint256,uint256,uint256,uint256,address,uint8,uint8,string,string,bool,uint256,(address[],uint256[])[],uint256),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,address),(uint8,uint8,address,uint8,uint256,uint256,uint256,uint256),uint256,uint256,bool))": FunctionFragment;
    "isOfferVoided(uint256)": FunctionFragment;
    "reserveRange(uint256,uint256,address)": FunctionFragment;
    "updateOfferMutualizer(uint256,address)": FunctionFragment;
    "updateOfferRoyaltyRecipients(uint256,(address[],uint256[]))": FunctionFragment;
    "updateOfferRoyaltyRecipientsBatch(uint256[],(address[],uint256[]))": FunctionFragment;
    "voidNonListedOffer(((uint256,uint256,uint256,uint256,uint256,uint256,address,uint8,uint8,string,string,bool,uint256,(address[],uint256[])[],uint256),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,address),(uint8,uint8,address,uint8,uint256,uint256,uint256,uint256),uint256,uint256,bool))": FunctionFragment;
    "voidNonListedOfferBatch(((uint256,uint256,uint256,uint256,uint256,uint256,address,uint8,uint8,string,string,bool,uint256,(address[],uint256[])[],uint256),(uint256,uint256,uint256,uint256),(uint256,uint256,uint256),(uint256,address),(uint8,uint8,address,uint8,uint256,uint256,uint256,uint256),uint256,uint256,bool)[])": FunctionFragment;
    "voidOffer(uint256)": FunctionFragment;
    "voidOfferBatch(uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createOffer",
    values: [
      BosonTypes.OfferStruct,
      BosonTypes.OfferDatesStruct,
      BosonTypes.OfferDurationsStruct,
      BosonTypes.DRParametersStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createOfferBatch",
    values: [
      BosonTypes.OfferStruct[],
      BosonTypes.OfferDatesStruct[],
      BosonTypes.OfferDurationsStruct[],
      BosonTypes.DRParametersStruct[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "extendOffer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extendOfferBatch",
    values: [BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentIdByOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextOfferId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferHash",
    values: [BosonTypes.FullOfferStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isOfferVoided",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveRange",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOfferMutualizer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOfferRoyaltyRecipients",
    values: [BigNumberish, BosonTypes.RoyaltyInfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOfferRoyaltyRecipientsBatch",
    values: [BigNumberish[], BosonTypes.RoyaltyInfoStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "voidNonListedOffer",
    values: [BosonTypes.FullOfferStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "voidNonListedOfferBatch",
    values: [BosonTypes.FullOfferStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voidOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voidOfferBatch",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOfferBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendOfferBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentIdByOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextOfferId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOfferHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOfferVoided",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOfferMutualizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOfferRoyaltyRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOfferRoyaltyRecipientsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voidNonListedOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voidNonListedOfferBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voidOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voidOfferBatch",
    data: BytesLike
  ): Result;

  events: {
    "NonListedOfferVoided(bytes32,uint256,address)": EventFragment;
    "OfferCreated(uint256,uint256,tuple,tuple,tuple,tuple,tuple,uint256,address)": EventFragment;
    "OfferExtended(uint256,uint256,uint256,address)": EventFragment;
    "OfferMutualizerUpdated(uint256,uint256,address,address)": EventFragment;
    "OfferRoyaltyInfoUpdated(uint256,uint256,tuple,address)": EventFragment;
    "OfferVoided(uint256,uint256,address)": EventFragment;
    "RangeReserved(uint256,uint256,uint256,uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NonListedOfferVoided"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferExtended"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferMutualizerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferRoyaltyInfoUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferVoided"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RangeReserved"): EventFragment;
}

export type NonListedOfferVoidedEvent = TypedEvent<
  [string, BigNumber, string],
  { offerHash: string; offererId: BigNumber; executedBy: string }
>;

export type NonListedOfferVoidedEventFilter =
  TypedEventFilter<NonListedOfferVoidedEvent>;

export type OfferCreatedEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    BosonTypes.OfferStructOutput,
    BosonTypes.OfferDatesStructOutput,
    BosonTypes.OfferDurationsStructOutput,
    BosonTypes.DisputeResolutionTermsStructOutput,
    BosonTypes.OfferFeesStructOutput,
    BigNumber,
    string
  ],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    offer: BosonTypes.OfferStructOutput;
    offerDates: BosonTypes.OfferDatesStructOutput;
    offerDurations: BosonTypes.OfferDurationsStructOutput;
    disputeResolutionTerms: BosonTypes.DisputeResolutionTermsStructOutput;
    offerFees: BosonTypes.OfferFeesStructOutput;
    agentId: BigNumber;
    executedBy: string;
  }
>;

export type OfferCreatedEventFilter = TypedEventFilter<OfferCreatedEvent>;

export type OfferExtendedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    validUntilDate: BigNumber;
    executedBy: string;
  }
>;

export type OfferExtendedEventFilter = TypedEventFilter<OfferExtendedEvent>;

export type OfferMutualizerUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    newMutualizer: string;
    executedBy: string;
  }
>;

export type OfferMutualizerUpdatedEventFilter =
  TypedEventFilter<OfferMutualizerUpdatedEvent>;

export type OfferRoyaltyInfoUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BosonTypes.RoyaltyInfoStructOutput, string],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    royaltyInfo: BosonTypes.RoyaltyInfoStructOutput;
    executedBy: string;
  }
>;

export type OfferRoyaltyInfoUpdatedEventFilter =
  TypedEventFilter<OfferRoyaltyInfoUpdatedEvent>;

export type OfferVoidedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { offerId: BigNumber; creatorId: BigNumber; executedBy: string }
>;

export type OfferVoidedEventFilter = TypedEventFilter<OfferVoidedEvent>;

export type RangeReservedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, string, string],
  {
    offerId: BigNumber;
    sellerId: BigNumber;
    startExchangeId: BigNumber;
    endExchangeId: BigNumber;
    owner: string;
    executedBy: string;
  }
>;

export type RangeReservedEventFilter = TypedEventFilter<RangeReservedEvent>;

export interface IBosonOfferHandler extends BaseContract {
  contractName: "IBosonOfferHandler";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBosonOfferHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _drParameters: BosonTypes.DRParametersStruct,
      _agentId: BigNumberish,
      _feeLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createOfferBatch(
      _offers: BosonTypes.OfferStruct[],
      _offerDates: BosonTypes.OfferDatesStruct[],
      _offerDurations: BosonTypes.OfferDurationsStruct[],
      _drParameters: BosonTypes.DRParametersStruct[],
      _agentIds: BigNumberish[],
      _feeLimits: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    extendOffer(
      _offerId: BigNumberish,
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    extendOfferBatch(
      _offerIds: BigNumberish[],
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAgentIdByOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { exists: boolean; agentId: BigNumber }>;

    getNextOfferId(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { nextOfferId: BigNumber }>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        BosonTypes.OfferStructOutput,
        BosonTypes.OfferDatesStructOutput,
        BosonTypes.OfferDurationsStructOutput,
        BosonTypes.DisputeResolutionTermsStructOutput,
        BosonTypes.OfferFeesStructOutput
      ] & {
        exists: boolean;
        offer: BosonTypes.OfferStructOutput;
        offerDates: BosonTypes.OfferDatesStructOutput;
        offerDurations: BosonTypes.OfferDurationsStructOutput;
        disputeResolutionTerms: BosonTypes.DisputeResolutionTermsStructOutput;
        offerFees: BosonTypes.OfferFeesStructOutput;
      }
    >;

    getOfferHash(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: CallOverrides
    ): Promise<[string] & { offerHash: string }>;

    isOfferVoided(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean] & { exists: boolean; offerVoided: boolean }>;

    reserveRange(
      _offerId: BigNumberish,
      _length: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateOfferMutualizer(
      _offerId: BigNumberish,
      _newMutualizer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateOfferRoyaltyRecipients(
      _offerId: BigNumberish,
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateOfferRoyaltyRecipientsBatch(
      _offerIds: BigNumberish[],
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voidNonListedOffer(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voidNonListedOfferBatch(
      _fullOffers: BosonTypes.FullOfferStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voidOfferBatch(
      _offerIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createOffer(
    _offer: BosonTypes.OfferStruct,
    _offerDates: BosonTypes.OfferDatesStruct,
    _offerDurations: BosonTypes.OfferDurationsStruct,
    _drParameters: BosonTypes.DRParametersStruct,
    _agentId: BigNumberish,
    _feeLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createOfferBatch(
    _offers: BosonTypes.OfferStruct[],
    _offerDates: BosonTypes.OfferDatesStruct[],
    _offerDurations: BosonTypes.OfferDurationsStruct[],
    _drParameters: BosonTypes.DRParametersStruct[],
    _agentIds: BigNumberish[],
    _feeLimits: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  extendOffer(
    _offerId: BigNumberish,
    _validUntilDate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  extendOfferBatch(
    _offerIds: BigNumberish[],
    _validUntilDate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAgentIdByOffer(
    _offerId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { exists: boolean; agentId: BigNumber }>;

  getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

  getOffer(
    _offerId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      BosonTypes.OfferStructOutput,
      BosonTypes.OfferDatesStructOutput,
      BosonTypes.OfferDurationsStructOutput,
      BosonTypes.DisputeResolutionTermsStructOutput,
      BosonTypes.OfferFeesStructOutput
    ] & {
      exists: boolean;
      offer: BosonTypes.OfferStructOutput;
      offerDates: BosonTypes.OfferDatesStructOutput;
      offerDurations: BosonTypes.OfferDurationsStructOutput;
      disputeResolutionTerms: BosonTypes.DisputeResolutionTermsStructOutput;
      offerFees: BosonTypes.OfferFeesStructOutput;
    }
  >;

  getOfferHash(
    _fullOffer: BosonTypes.FullOfferStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  isOfferVoided(
    _offerId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean] & { exists: boolean; offerVoided: boolean }>;

  reserveRange(
    _offerId: BigNumberish,
    _length: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateOfferMutualizer(
    _offerId: BigNumberish,
    _newMutualizer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateOfferRoyaltyRecipients(
    _offerId: BigNumberish,
    _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateOfferRoyaltyRecipientsBatch(
    _offerIds: BigNumberish[],
    _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voidNonListedOffer(
    _fullOffer: BosonTypes.FullOfferStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voidNonListedOfferBatch(
    _fullOffers: BosonTypes.FullOfferStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voidOffer(
    _offerId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voidOfferBatch(
    _offerIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _drParameters: BosonTypes.DRParametersStruct,
      _agentId: BigNumberish,
      _feeLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createOfferBatch(
      _offers: BosonTypes.OfferStruct[],
      _offerDates: BosonTypes.OfferDatesStruct[],
      _offerDurations: BosonTypes.OfferDurationsStruct[],
      _drParameters: BosonTypes.DRParametersStruct[],
      _agentIds: BigNumberish[],
      _feeLimits: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    extendOffer(
      _offerId: BigNumberish,
      _validUntilDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    extendOfferBatch(
      _offerIds: BigNumberish[],
      _validUntilDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAgentIdByOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { exists: boolean; agentId: BigNumber }>;

    getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        BosonTypes.OfferStructOutput,
        BosonTypes.OfferDatesStructOutput,
        BosonTypes.OfferDurationsStructOutput,
        BosonTypes.DisputeResolutionTermsStructOutput,
        BosonTypes.OfferFeesStructOutput
      ] & {
        exists: boolean;
        offer: BosonTypes.OfferStructOutput;
        offerDates: BosonTypes.OfferDatesStructOutput;
        offerDurations: BosonTypes.OfferDurationsStructOutput;
        disputeResolutionTerms: BosonTypes.DisputeResolutionTermsStructOutput;
        offerFees: BosonTypes.OfferFeesStructOutput;
      }
    >;

    getOfferHash(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    isOfferVoided(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean] & { exists: boolean; offerVoided: boolean }>;

    reserveRange(
      _offerId: BigNumberish,
      _length: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOfferMutualizer(
      _offerId: BigNumberish,
      _newMutualizer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOfferRoyaltyRecipients(
      _offerId: BigNumberish,
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOfferRoyaltyRecipientsBatch(
      _offerIds: BigNumberish[],
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    voidNonListedOffer(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    voidNonListedOfferBatch(
      _fullOffers: BosonTypes.FullOfferStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    voidOffer(_offerId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    voidOfferBatch(
      _offerIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NonListedOfferVoided(bytes32,uint256,address)"(
      offerHash?: null,
      offererId?: BigNumberish | null,
      executedBy?: string | null
    ): NonListedOfferVoidedEventFilter;
    NonListedOfferVoided(
      offerHash?: null,
      offererId?: BigNumberish | null,
      executedBy?: string | null
    ): NonListedOfferVoidedEventFilter;

    "OfferCreated(uint256,uint256,tuple,tuple,tuple,tuple,tuple,uint256,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      offer?: null,
      offerDates?: null,
      offerDurations?: null,
      disputeResolutionTerms?: null,
      offerFees?: null,
      agentId?: BigNumberish | null,
      executedBy?: null
    ): OfferCreatedEventFilter;
    OfferCreated(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      offer?: null,
      offerDates?: null,
      offerDurations?: null,
      disputeResolutionTerms?: null,
      offerFees?: null,
      agentId?: BigNumberish | null,
      executedBy?: null
    ): OfferCreatedEventFilter;

    "OfferExtended(uint256,uint256,uint256,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      validUntilDate?: null,
      executedBy?: string | null
    ): OfferExtendedEventFilter;
    OfferExtended(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      validUntilDate?: null,
      executedBy?: string | null
    ): OfferExtendedEventFilter;

    "OfferMutualizerUpdated(uint256,uint256,address,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      newMutualizer?: string | null,
      executedBy?: null
    ): OfferMutualizerUpdatedEventFilter;
    OfferMutualizerUpdated(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      newMutualizer?: string | null,
      executedBy?: null
    ): OfferMutualizerUpdatedEventFilter;

    "OfferRoyaltyInfoUpdated(uint256,uint256,tuple,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      royaltyInfo?: null,
      executedBy?: string | null
    ): OfferRoyaltyInfoUpdatedEventFilter;
    OfferRoyaltyInfoUpdated(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      royaltyInfo?: null,
      executedBy?: string | null
    ): OfferRoyaltyInfoUpdatedEventFilter;

    "OfferVoided(uint256,uint256,address)"(
      offerId?: BigNumberish | null,
      creatorId?: BigNumberish | null,
      executedBy?: string | null
    ): OfferVoidedEventFilter;
    OfferVoided(
      offerId?: BigNumberish | null,
      creatorId?: BigNumberish | null,
      executedBy?: string | null
    ): OfferVoidedEventFilter;

    "RangeReserved(uint256,uint256,uint256,uint256,address,address)"(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      startExchangeId?: null,
      endExchangeId?: null,
      owner?: null,
      executedBy?: string | null
    ): RangeReservedEventFilter;
    RangeReserved(
      offerId?: BigNumberish | null,
      sellerId?: BigNumberish | null,
      startExchangeId?: null,
      endExchangeId?: null,
      owner?: null,
      executedBy?: string | null
    ): RangeReservedEventFilter;
  };

  estimateGas: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _drParameters: BosonTypes.DRParametersStruct,
      _agentId: BigNumberish,
      _feeLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createOfferBatch(
      _offers: BosonTypes.OfferStruct[],
      _offerDates: BosonTypes.OfferDatesStruct[],
      _offerDurations: BosonTypes.OfferDurationsStruct[],
      _drParameters: BosonTypes.DRParametersStruct[],
      _agentIds: BigNumberish[],
      _feeLimits: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    extendOffer(
      _offerId: BigNumberish,
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    extendOfferBatch(
      _offerIds: BigNumberish[],
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAgentIdByOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextOfferId(overrides?: CallOverrides): Promise<BigNumber>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOfferHash(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOfferVoided(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reserveRange(
      _offerId: BigNumberish,
      _length: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateOfferMutualizer(
      _offerId: BigNumberish,
      _newMutualizer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateOfferRoyaltyRecipients(
      _offerId: BigNumberish,
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateOfferRoyaltyRecipientsBatch(
      _offerIds: BigNumberish[],
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voidNonListedOffer(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voidNonListedOfferBatch(
      _fullOffers: BosonTypes.FullOfferStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voidOfferBatch(
      _offerIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createOffer(
      _offer: BosonTypes.OfferStruct,
      _offerDates: BosonTypes.OfferDatesStruct,
      _offerDurations: BosonTypes.OfferDurationsStruct,
      _drParameters: BosonTypes.DRParametersStruct,
      _agentId: BigNumberish,
      _feeLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createOfferBatch(
      _offers: BosonTypes.OfferStruct[],
      _offerDates: BosonTypes.OfferDatesStruct[],
      _offerDurations: BosonTypes.OfferDurationsStruct[],
      _drParameters: BosonTypes.DRParametersStruct[],
      _agentIds: BigNumberish[],
      _feeLimits: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    extendOffer(
      _offerId: BigNumberish,
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    extendOfferBatch(
      _offerIds: BigNumberish[],
      _validUntilDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAgentIdByOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNextOfferId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOffer(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOfferHash(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOfferVoided(
      _offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserveRange(
      _offerId: BigNumberish,
      _length: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateOfferMutualizer(
      _offerId: BigNumberish,
      _newMutualizer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateOfferRoyaltyRecipients(
      _offerId: BigNumberish,
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateOfferRoyaltyRecipientsBatch(
      _offerIds: BigNumberish[],
      _royaltyInfo: BosonTypes.RoyaltyInfoStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voidNonListedOffer(
      _fullOffer: BosonTypes.FullOfferStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voidNonListedOfferBatch(
      _fullOffers: BosonTypes.FullOfferStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voidOffer(
      _offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voidOfferBatch(
      _offerIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
