/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace BosonTypes {
  export type MetaTxExchangeDetailsStruct = { exchangeId: BigNumberish };

  export type MetaTxExchangeDetailsStructOutput = [BigNumber] & {
    exchangeId: BigNumber;
  };

  export type MetaTxOfferDetailsStruct = {
    buyer: string;
    offerId: BigNumberish;
  };

  export type MetaTxOfferDetailsStructOutput = [string, BigNumber] & {
    buyer: string;
    offerId: BigNumber;
  };

  export type MetaTxDisputeDetailsStruct = {
    exchangeId: BigNumberish;
    complaint: string;
  };

  export type MetaTxDisputeDetailsStructOutput = [BigNumber, string] & {
    exchangeId: BigNumber;
    complaint: string;
  };

  export type MetaTxDisputeResolutionDetailsStruct = {
    exchangeId: BigNumberish;
    buyerPercent: BigNumberish;
    sigR: BytesLike;
    sigS: BytesLike;
    sigV: BigNumberish;
  };

  export type MetaTxDisputeResolutionDetailsStructOutput = [
    BigNumber,
    BigNumber,
    string,
    string,
    number
  ] & {
    exchangeId: BigNumber;
    buyerPercent: BigNumber;
    sigR: string;
    sigS: string;
    sigV: number;
  };

  export type MetaTxFundDetailsStruct = {
    entityId: BigNumberish;
    tokenList: string[];
    tokenAmounts: BigNumberish[];
  };

  export type MetaTxFundDetailsStructOutput = [
    BigNumber,
    string[],
    BigNumber[]
  ] & { entityId: BigNumber; tokenList: string[]; tokenAmounts: BigNumber[] };
}

export interface IBosonMetaTransactionsHandlerInterface
  extends utils.Interface {
  contractName: "IBosonMetaTransactionsHandler";
  functions: {
    "executeMetaTransaction(address,string,bytes,uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxCancelVoucher(address,(uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxCommitToOffer(address,(address,uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxCompleteExchange(address,(uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxEscalateDispute(address,(uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxRaiseDispute(address,(uint256,string),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxRedeemVoucher(address,(uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxResolveDispute(address,(uint256,uint256,bytes32,bytes32,uint8),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxRetractDispute(address,(uint256),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "executeMetaTxWithdrawFunds(address,(uint256,address[],uint256[]),uint256,bytes32,bytes32,uint8)": FunctionFragment;
    "isUsedNonce(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeMetaTransaction",
    values: [
      string,
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxCancelVoucher",
    values: [
      string,
      BosonTypes.MetaTxExchangeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxCommitToOffer",
    values: [
      string,
      BosonTypes.MetaTxOfferDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxCompleteExchange",
    values: [
      string,
      BosonTypes.MetaTxExchangeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxEscalateDispute",
    values: [
      string,
      BosonTypes.MetaTxExchangeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxRaiseDispute",
    values: [
      string,
      BosonTypes.MetaTxDisputeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxRedeemVoucher",
    values: [
      string,
      BosonTypes.MetaTxExchangeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxResolveDispute",
    values: [
      string,
      BosonTypes.MetaTxDisputeResolutionDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxRetractDispute",
    values: [
      string,
      BosonTypes.MetaTxExchangeDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTxWithdrawFunds",
    values: [
      string,
      BosonTypes.MetaTxFundDetailsStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isUsedNonce",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeMetaTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxCancelVoucher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxCommitToOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxCompleteExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxEscalateDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxRaiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxRedeemVoucher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxResolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxRetractDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTxWithdrawFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUsedNonce",
    data: BytesLike
  ): Result;

  events: {
    "MetaTransactionExecuted(address,address,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MetaTransactionExecuted"): EventFragment;
}

export type MetaTransactionExecutedEvent = TypedEvent<
  [string, string, string, BigNumber],
  {
    userAddress: string;
    relayerAddress: string;
    functionName: string;
    nonce: BigNumber;
  }
>;

export type MetaTransactionExecutedEventFilter =
  TypedEventFilter<MetaTransactionExecutedEvent>;

export interface IBosonMetaTransactionsHandler extends BaseContract {
  contractName: "IBosonMetaTransactionsHandler";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBosonMetaTransactionsHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    executeMetaTransaction(
      _userAddress: string,
      _functionName: string,
      _functionSignature: BytesLike,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxCancelVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxCommitToOffer(
      _userAddress: string,
      _offerDetails: BosonTypes.MetaTxOfferDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxCompleteExchange(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxEscalateDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxRaiseDispute(
      _userAddress: string,
      _disputeDetails: BosonTypes.MetaTxDisputeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxRedeemVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxResolveDispute(
      _userAddress: string,
      _disputeResolutionDetails: BosonTypes.MetaTxDisputeResolutionDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxRetractDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeMetaTxWithdrawFunds(
      _userAddress: string,
      _fundDetails: BosonTypes.MetaTxFundDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isUsedNonce(
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  executeMetaTransaction(
    _userAddress: string,
    _functionName: string,
    _functionSignature: BytesLike,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxCancelVoucher(
    _userAddress: string,
    _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxCommitToOffer(
    _userAddress: string,
    _offerDetails: BosonTypes.MetaTxOfferDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxCompleteExchange(
    _userAddress: string,
    _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxEscalateDispute(
    _userAddress: string,
    _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxRaiseDispute(
    _userAddress: string,
    _disputeDetails: BosonTypes.MetaTxDisputeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxRedeemVoucher(
    _userAddress: string,
    _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxResolveDispute(
    _userAddress: string,
    _disputeResolutionDetails: BosonTypes.MetaTxDisputeResolutionDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxRetractDispute(
    _userAddress: string,
    _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeMetaTxWithdrawFunds(
    _userAddress: string,
    _fundDetails: BosonTypes.MetaTxFundDetailsStruct,
    _nonce: BigNumberish,
    _sigR: BytesLike,
    _sigS: BytesLike,
    _sigV: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isUsedNonce(
    _nonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    executeMetaTransaction(
      _userAddress: string,
      _functionName: string,
      _functionSignature: BytesLike,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxCancelVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxCommitToOffer(
      _userAddress: string,
      _offerDetails: BosonTypes.MetaTxOfferDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxCompleteExchange(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxEscalateDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxRaiseDispute(
      _userAddress: string,
      _disputeDetails: BosonTypes.MetaTxDisputeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxRedeemVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxResolveDispute(
      _userAddress: string,
      _disputeResolutionDetails: BosonTypes.MetaTxDisputeResolutionDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxRetractDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeMetaTxWithdrawFunds(
      _userAddress: string,
      _fundDetails: BosonTypes.MetaTxFundDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isUsedNonce(
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "MetaTransactionExecuted(address,address,string,uint256)"(
      userAddress?: string | null,
      relayerAddress?: string | null,
      functionName?: string | null,
      nonce?: null
    ): MetaTransactionExecutedEventFilter;
    MetaTransactionExecuted(
      userAddress?: string | null,
      relayerAddress?: string | null,
      functionName?: string | null,
      nonce?: null
    ): MetaTransactionExecutedEventFilter;
  };

  estimateGas: {
    executeMetaTransaction(
      _userAddress: string,
      _functionName: string,
      _functionSignature: BytesLike,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxCancelVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxCommitToOffer(
      _userAddress: string,
      _offerDetails: BosonTypes.MetaTxOfferDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxCompleteExchange(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxEscalateDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxRaiseDispute(
      _userAddress: string,
      _disputeDetails: BosonTypes.MetaTxDisputeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxRedeemVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxResolveDispute(
      _userAddress: string,
      _disputeResolutionDetails: BosonTypes.MetaTxDisputeResolutionDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxRetractDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeMetaTxWithdrawFunds(
      _userAddress: string,
      _fundDetails: BosonTypes.MetaTxFundDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isUsedNonce(
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeMetaTransaction(
      _userAddress: string,
      _functionName: string,
      _functionSignature: BytesLike,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxCancelVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxCommitToOffer(
      _userAddress: string,
      _offerDetails: BosonTypes.MetaTxOfferDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxCompleteExchange(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxEscalateDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxRaiseDispute(
      _userAddress: string,
      _disputeDetails: BosonTypes.MetaTxDisputeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxRedeemVoucher(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxResolveDispute(
      _userAddress: string,
      _disputeResolutionDetails: BosonTypes.MetaTxDisputeResolutionDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxRetractDispute(
      _userAddress: string,
      _exchangeDetails: BosonTypes.MetaTxExchangeDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeMetaTxWithdrawFunds(
      _userAddress: string,
      _fundDetails: BosonTypes.MetaTxFundDetailsStruct,
      _nonce: BigNumberish,
      _sigR: BytesLike,
      _sigS: BytesLike,
      _sigV: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isUsedNonce(
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
