name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls
      - run: cd packages/react-kit
      - run: pwd
      - run: ls
      - run: mv .env.test .env
      - run: ls
      - run: cat .env
      - name: Install dependencies
        run: npm ci
      - id: build
        run: npm run build -- --cache-dir=".turbo"
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/react-kit
        env:
          STORYBOOK_INFURA_PROJECT_SECRET: ${{ secrets.STORYBOOK_INFURA_PROJECT_SECRET }}
          STORYBOOK_REACT_APP_MAGIC_API_KEY: ${{ secrets.STORYBOOK_REACT_APP_MAGIC_API_KEY }}
