name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}
      - run: npm ci
      - run: npm run lint -- --cache-dir=".turbo"
      - run: npm run build -- --cache-dir=".turbo"
      - run: npm run test -- --cache-dir=".turbo"
      - run: npm run test:badge -- --cache-dir=".turbo"
      # - name: Commit files
      #   run: |
      #     git config --local user.email "bapp-ci-bot@users.noreply.github.com"
      #     git config --local user.name "@bapp-ci-bot"
      #     git commit -am "Update badges"
      # - name: Update badges
      #   run: |
      #     git push
