name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run lint --concurrency=1
      - run: npm run build
      - run: npm run test --concurrency=1
