name: Deploy subgraph to testing env

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ORMI_0x_GRAPH_API_KEY_TESTING:
        required: true
      BSNORG_ACTIONS_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy subgraph
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}
      - run: npm ci
      - id: build
        run: npm run build -- --cache-dir=".turbo"
      - name: Set github bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Authenticate The Graph CLI
        run: npx graph auth https://api.0xgraph.xyz/deploy/ ${{ secrets.ORMI_0x_GRAPH_API_KEY_TESTING }}
      - name: Deploy subgraph to amoy
        run: cd ./packages/subgraph && npm run deploy:testing:amoy
        env:
          ORMI_0x_GRAPH_API_KEY: ${{ secrets.ORMI_0x_GRAPH_API_KEY_TESTING }}
      - name: Deploy subgraph to sepolia
        run: cd ./packages/subgraph && npm run deploy:testing:sepolia
        env:
          ORMI_0x_GRAPH_API_KEY: ${{ secrets.ORMI_0x_GRAPH_API_KEY_TESTING }}
      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.BSNORG_ACTIONS_SECRET }}
          GITHUB_TOKEN: ${{ secrets.BSNORG_ACTIONS_SECRET }}
        run: |
          git add .
          git commit -m "chore: deploy testing subgraphs [skip ci]"
          git push
