name: Deploy widgets to IPFS

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-widgets-actions
    # tags:
    #   - '@bosonprotocol\/widgets@[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy widgets to IPFS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Deploy via fleek
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: ./packages/widgets
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
