name: Deploy subgraph

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      subgraphVersion:
        description: "Subgraph version"
        required: true
        default: "0.0.1"
        type: string
      deployTarget:
        description: "Deploy target env"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
  push:
    tags:
      - '@bosonprotocol\/subgraph@[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy subgraph
    env:
      DEPLOY_TARGET: ${{ github.event.inputs.deployTarget }}
      SUBGRAPH_VERSION: ${{ github.event.inputs.subgraphVersion }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - name: Authenticate The Graph CLI
        run: npx graph auth --product hosted-service ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
      - name: Deploy subgraph
        run: cd ./packages/subgraph && npm run deploy:${{ env.DEPLOY_TARGET }} -- -l ${{ env.SUBGRAPH_VERSION }}
