name: Deploy subgraph to staging env

on:
  push:
    tags:
      - '@bosonprotocol\/subgraph@[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy subgraph
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - name: Authenticate The Graph CLI
        run: npx graph auth --product hosted-service ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}
      - name: Deploy subgraph
        run: cd ./packages/subgraph && npm run deploy:staging -- -l 0.0.1
