name: Deploy subgraph to staging env

on:
  workflow_dispatch:
    branches: [main]
  release:
    types: [published]

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, '@bosonprotocol/subgraph@')
    runs-on: ubuntu-latest
    name: Deploy subgraph
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}
      - run: npm ci
      - id: build
        run: npm run build -- --cache-dir=".turbo"
      - name: Authenticate The Graph CLI
        run: npx graph auth --product hosted-service ${{ secrets.THE_GRAPH_ACCESS_TOKEN_STAGING }}
      - name: Deploy subgraph to amoy
        run: cd ./packages/subgraph && npm run deploy:staging:amoy
      - name: Deploy subgraph to sepolia
        run: cd ./packages/subgraph && npm run deploy:staging:sepolia
