name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          scopes: |
            contracts-sdk
            core-sdk
            data-storage-sdk
            subgraph
            widgets
            widgets-sdk
          subjectPattern: ^(?![A-Z]).+$
          validateSingleCommit: true
