name: "Publish release"

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        default: "release"
        type: choice
        options:
          - prerelease
          - release

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.PAT }}
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - run: npm run ci
      - run: npm run build
      - name: Bump version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if [ ${{ github.event.inputs.releaseType }} = release ]; then
            lerna version --conventional-graduate --yes
          else
            lerna version --conventional-prerelease --preid next --yes
          fi
      - name: Pack package
        run: yarn workspaces foreach --no-private pack
      - name: Publish to registry
        run: |
          if [ ${{ github.event.inputs.releaseType }} = release ]; then
            echo "Publish latest..."
            lerna exec --no-private -- npm publish package.tgz --tag latest
          else
            echo "Publish next..."
            lerna exec --no-private -- npm publish package.tgz --tag next
          fi
